FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y \
    cmake \
    gcc \
    gcovr \
    libc6-dev \
    patch \
    xz-utils \
    gcc-arm-none-eabi \
    binutils-arm-none-eabi \
    && rm -rf /var/lib/apt/lists/*
